### PR TITLE
feat: add contents md files, slides, and notebooks for sessions 7 & 8 in data structures series

### PR DESCRIPTION
**Pull request by nayeonshin**
Added files for the Sessions #7 Heaps and #8 Graphs in Intro to Data Structures with Python: Ace the Technical Interview series

Files added:
In <code>WWCodePython/DataStructuresseries/contents</code>
<code>Session #7 Heaps [June 3, 2021].md</code>
<code>Session #8 Graphs [June 24, 2021].md</code>

In <code>WWCodePython/DataStructuresseries/notebooks</code>
<code>Session #7 Heaps [June 3, 2021].ipynb</code>
<code>Session #8 Graphs [June 24, 2021].ipynb</code>

In <code>WWCodePython/DataStructuresseries/slides</code>
<code>Session #7 Heaps [June 3, 2021].pdf</code>
<code>Session #8 Graphs [June 24, 2021].pdf</code>

### CODE REVIEW

**Review by varchanaiyer — CHANGES_REQUESTED** [review]
Hii! can you add your slides as a pdf to the slides folder on the repo: https://github.com/WomenWhoCode/WWCodePython/tree/master/DataStructuresseries/slides

**Comment by nayeonshin** [comment]
Hm, interesting. I've already added <code>Session #7 Heaps [June 3, 2021].pdf</code> and <code>Session #8 Graphs [June 24, 2021].pdf</code> in the <code>slides</code> directory. I see their existence in the commit history, but please let me know again if you can't see the pdf files!

**Comment by varchanaiyer** [comment]
Can you refer to the slides on the main contents file: Session #7 Heaps.md. I still see the link to Google Slides

**Comment by nayeonshin** [comment]
Sorry about it, I thought you were referring to the pdf files in the <code>slides</code> folder! Now I changed the link to the slides in <code>contents</code>

**Review by varchanaiyer — APPROVED** [review]
Awesome! Thanks Nayeon, I am approving this

**Pull request merged**
